#!/usr/bin/env python3
"""B3 -- capture a consumer group's committed offsets before a change, and emit
an exact, runnable restore.

The rollback this produces is for **offsets only**. Rolling back the
*deployment* -- rebuilding the image with the previous provider wheel -- is a
separate operation with a separate owner. Conflating the two is the most common
way an offset incident turns into two incidents, so the generated runbook says
so in the file itself.

Writes three files into the change directory:

    pre-offsets.json      full state, including high watermarks, for the record
    restore-offsets.csv   topic,partition,offset -- kafka's --from-file format
    restore.sh            the one command to run, with its own preflight

Why the high watermarks are captured too
----------------------------------------
Restoring an offset is only safe if the messages are still there. Kafka
retention can delete the segment you were planning to replay, and the restore
then succeeds while silently landing out of range. ``restore.sh`` re-checks the
earliest offset at restore time and refuses if the captured position has aged
out of the log.

Exit codes: 0 captured, 1 broker error, 2 bad usage.
"""

from __future__ import annotations

import argparse
import datetime as dt
import json
import os
import stat
import sys

from confluent_kafka import OFFSET_INVALID, ConsumerGroupTopicPartitions, TopicPartition
from confluent_kafka.admin import AdminClient, OffsetSpec

SCHEMA_VERSION = 1
EXIT_OK, EXIT_ERROR, EXIT_USAGE = 0, 1, 2


def die(message: str, code: int = EXIT_USAGE) -> None:
    print(message, file=sys.stderr)
    sys.exit(code)


RESTORE_SH = """#!/usr/bin/env bash
#
# Restore committed offsets for consumer group '{group}' to the state captured
# at {captured_at}.
#
# SCOPE: offsets only. This does NOT roll back the deployed provider wheel --
# that is `docker build --build-arg WHEEL=<previous> && docker compose up -d` in
# deploy/production/, and it is a different owner's call. If you are here
# because a bad operator shipped, you probably need both, in that order:
# deployment first, then offsets.
#
# Generated by tools/capture_offsets.py. Safe to re-run: setting an offset to a
# value it already holds is a no-op.
#
set -euo pipefail

CONTAINER="${{CONTAINER:-{container}}}"
BOOTSTRAP="${{BOOTSTRAP:-{bootstrap}}}"
GROUP="{group}"
CSV="$(cd "$(dirname "${{BASH_SOURCE[0]}}")" && pwd)/restore-offsets.csv"

K() {{ docker exec -i "${{CONTAINER}}" "/opt/kafka/bin/$1" --bootstrap-server "${{BOOTSTRAP}}" "${{@:2}}"; }}

echo "== preflight =="

# 1. The group must have no active members. alter/reset is rejected otherwise,
#    and finding that out halfway through a restore is the worst time.
state=$(K kafka-consumer-groups.sh --describe --group "${{GROUP}}" --state \\
        | awk -v g="${{GROUP}}" '$1 == g {{print $(NF-1)}}' | head -1)
if [ "${{state}}" != "Empty" ]; then
  echo "REFUSING: group is '${{state}}', expected 'Empty'." >&2
  echo "Stop the consumers before restoring offsets." >&2
  exit 1
fi
echo "  group state: Empty"

# 2. Retention may have deleted the messages this restore points at. The reset
#    would succeed and silently leave the group out of range, where the consumer
#    then applies auto.offset.reset and the restore quietly does nothing useful.
fail=0
while IFS=, read -r topic partition offset; do
  earliest=$(K kafka-get-offsets.sh --topic "$topic" --partitions "$partition" \\
             --time earliest | awk -F: '{{print $3}}')
  if [ "$offset" -lt "$earliest" ]; then
    echo "REFUSING: $topic:$partition captured offset $offset is below the current" >&2
    echo "  earliest offset $earliest -- retention has deleted those messages." >&2
    fail=1
  fi
done < "${{CSV}}"
[ "$fail" -eq 0 ] || exit 1
echo "  all captured offsets still within retention"

echo "== restoring =="
docker cp "${{CSV}}" "${{CONTAINER}}:/tmp/restore-offsets.csv"
K kafka-consumer-groups.sh --group "${{GROUP}}" --reset-offsets \\
  --from-file /tmp/restore-offsets.csv --execute

echo "== verify =="
K kafka-consumer-groups.sh --describe --group "${{GROUP}}"
"""


def capture(admin: AdminClient, group: str, topic_filter: str | None, timeout: float) -> dict:
    futures = admin.list_consumer_group_offsets(
        [ConsumerGroupTopicPartitions(group)], request_timeout=timeout
    )
    result = next(iter(futures.values())).result()

    committed = [
        tp
        for tp in result.topic_partitions
        if tp.offset != OFFSET_INVALID and (topic_filter is None or tp.topic == topic_filter)
    ]
    if not committed:
        scope = f" for topic {topic_filter!r}" if topic_filter else ""
        die(
            f"group {group!r} has no committed offsets{scope}. Nothing to capture, "
            f"which also means there is nothing to restore -- do not proceed as if "
            f"a rollback exists.",
            EXIT_ERROR,
        )

    # Watermarks are captured so restore.sh can detect retention loss later.
    request_lo = {TopicPartition(tp.topic, tp.partition): OffsetSpec.earliest() for tp in committed}
    request_hi = {TopicPartition(tp.topic, tp.partition): OffsetSpec.latest() for tp in committed}
    lo = {
        (tp.topic, tp.partition): f.result().offset
        for tp, f in admin.list_offsets(request_lo, request_timeout=timeout).items()
    }
    hi = {
        (tp.topic, tp.partition): f.result().offset
        for tp, f in admin.list_offsets(request_hi, request_timeout=timeout).items()
    }

    # Sorted so re-capturing an unchanged group produces a byte-identical file
    # and shows up as "no diff" in the change trail.
    rows = sorted(
        (
            {
                "topic": tp.topic,
                "partition": tp.partition,
                "committed": tp.offset,
                "earliest": lo[(tp.topic, tp.partition)],
                "latest": hi[(tp.topic, tp.partition)],
                "lag": hi[(tp.topic, tp.partition)] - tp.offset,
            }
            for tp in committed
        ),
        key=lambda r: (r["topic"], r["partition"]),
    )
    return {
        "schema_version": SCHEMA_VERSION,
        "captured_at": dt.datetime.now(dt.timezone.utc).isoformat(timespec="seconds"),
        "group": group,
        "topic_filter": topic_filter,
        "partitions": rows,
        "totals": {"lag": sum(r["lag"] for r in rows), "partitions": len(rows)},
    }


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(
        description="Capture pre-change consumer-group offsets and emit an exact restore.",
        epilog="Offsets only. Deployment rollback is a separate operation -- see restore.sh.",
    )
    ap.add_argument("--group", required=True)
    ap.add_argument("--topic", help="restrict to one topic (default: every topic the group holds)")
    ap.add_argument("--bootstrap", default="localhost:9092")
    ap.add_argument("--container", default="kafka", help="Kafka container name used by restore.sh")
    ap.add_argument(
        "--change-dir",
        required=True,
        metavar="DIR",
        help="e.g. docs/changes/CHG-001 -- created if absent",
    )
    ap.add_argument("--timeout", type=float, default=10.0)
    args = ap.parse_args(argv)

    admin = AdminClient({"bootstrap.servers": args.bootstrap})
    state = capture(admin, args.group, args.topic, args.timeout)
    state["bootstrap"] = args.bootstrap

    os.makedirs(args.change_dir, exist_ok=True)
    json_path = os.path.join(args.change_dir, "pre-offsets.json")
    csv_path = os.path.join(args.change_dir, "restore-offsets.csv")
    sh_path = os.path.join(args.change_dir, "restore.sh")

    with open(json_path, "w") as fh:
        json.dump(state, fh, indent=2)
        fh.write("\n")

    # kafka-consumer-groups.sh --from-file expects bare topic,partition,offset
    # with no header. A header line is parsed as data and fails with a
    # NumberFormatException that names neither the file nor the line.
    with open(csv_path, "w") as fh:
        for r in state["partitions"]:
            fh.write(f"{r['topic']},{r['partition']},{r['committed']}\n")

    with open(sh_path, "w") as fh:
        fh.write(
            RESTORE_SH.format(
                group=args.group,
                captured_at=state["captured_at"],
                container=args.container,
                bootstrap=args.bootstrap,
            )
        )
    os.chmod(sh_path, os.stat(sh_path).st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)

    print(f"captured {state['totals']['partitions']} partition(s) for group {args.group!r}")
    for r in state["partitions"]:
        print(f"  {r['topic']}:{r['partition']}  committed={r['committed']}  lag={r['lag']}")
    print(f"\nwrote:\n  {json_path}\n  {csv_path}\n  {sh_path}")
    print(f"\nto roll back OFFSETS (not the deployment):\n  {sh_path}")
    return EXIT_OK


if __name__ == "__main__":
    sys.exit(main())
