#!/usr/bin/env python3
"""The deterministic half of the rule pack. **There is no model in this path.**

Reads ``rules/*.yaml`` and reports violations. Same data the Cursor agent gets
as context (via ``.cursor/rules/*.mdc``, generated by ``gen_rules.py``), same
data the humans read (``docs/RULES.md``) -- but here it is a detector that
either fires or does not, offline, in well under a second.

That split is the answer to two questions the room will ask:

  "This is just prompt engineering."
      The agent explains and fixes. This file decides. It imports nothing but
      the standard library and PyYAML, and its verdict does not depend on a
      model, a temperature, or a prompt.

  "What happens when you leave?"
      The rules are data with named owners. Adding one is a YAML file, not a
      code change. The evaluator below is ~350 lines and has no domain
      knowledge in it at all.

Design rules, deliberately the same three that govern policy_check.py -- this
tool is the one place a new engineer will look to learn what "our conventions"
means, so it had better follow them:

  1. **An unknown detector kind is a hard error (exit 2), not a skip.** A typo'd
     kind that silently passed would be a linter reporting clean while checking
     nothing.
  2. **Fail closed.** An exception inside a detector becomes a violation
     attributed to that rule, not a swallowed traceback.
  3. **Rules that could not be evaluated are reported, not hidden.** A rule
     whose registry file or test root is absent from this checkout is listed
     under "not evaluated" so the clean run cannot be mistaken for coverage.

Exit codes: 0 clean, 1 violations found, 2 bad usage / malformed rules.
(2 is distinct on purpose: a broken rule pack must not look like a clean run,
and it must not look like a failing one either.)
"""

from __future__ import annotations

import argparse
import ast
import fnmatch
import json
import os
import re
import sys
from dataclasses import dataclass, field
from typing import Callable

import yaml

EXIT_CLEAN, EXIT_VIOLATIONS, EXIT_BADINPUT = 0, 1, 2

SEVERITIES = ("error", "advisory")


def die(message: str) -> None:
    """Exit 2. Deliberately not `raise SystemExit(msg)`, which exits 1 and would
    be indistinguishable from 'the linter found something'."""
    print(message, file=sys.stderr)
    sys.exit(EXIT_BADINPUT)


# ---------------------------------------------------------------------------
# Model
# ---------------------------------------------------------------------------


@dataclass
class Rule:
    id: str
    pack: str
    title: str
    severity: str
    owner: str
    applies_to: list[str]
    detector: dict | None
    message: str
    rationale: str = ""
    evidence: str = ""
    replacement: str = ""
    references: list[str] = field(default_factory=list)
    source_file: str = ""


@dataclass
class Finding:
    rule: str
    severity: str
    path: str
    line: int
    message: str
    title: str = ""


@dataclass
class Context:
    """Everything a detector may look at for one file."""

    root: str
    relpath: str
    abspath: str
    source: str
    tree: ast.AST | None


# ---------------------------------------------------------------------------
# Glob matching
#
# fnmatch treats `**` as `*`, so `providers/**/*.py` would match
# `providers/x.py` but not `providers/a/b/x.py`. The applies_to patterns are
# load-bearing -- a rule that silently matches nothing is worse than no rule --
# so translate properly instead.
# ---------------------------------------------------------------------------


def _glob_to_regex(pattern: str) -> re.Pattern:
    i, n, out = 0, len(pattern), []
    while i < n:
        if pattern.startswith("**/", i):
            out.append("(?:.*/)?")
            i += 3
        elif pattern.startswith("**", i):
            out.append(".*")
            i += 2
        elif pattern[i] == "*":
            out.append("[^/]*")
            i += 1
        elif pattern[i] == "?":
            out.append("[^/]")
            i += 1
        else:
            out.append(re.escape(pattern[i]))
            i += 1
    return re.compile("^" + "".join(out) + "$")


_GLOB_CACHE: dict[str, re.Pattern] = {}


def matches(relpath: str, patterns: list[str]) -> bool:
    rel = relpath.replace(os.sep, "/")
    for pat in patterns:
        rx = _GLOB_CACHE.get(pat)
        if rx is None:
            rx = _GLOB_CACHE[pat] = _glob_to_regex(pat)
        if rx.match(rel):
            return True
    return False


# ---------------------------------------------------------------------------
# Detectors
#
# One function per `detector.kind`. Each returns a list of Findings, or raises
# SkipRule when this checkout does not contain what the rule needs to be
# evaluated (see design rule 3).
# ---------------------------------------------------------------------------


class SkipRule(Exception):
    """Raised by a detector that cannot evaluate here. Reported, never hidden."""


DETECTORS: dict[str, Callable[[Rule, Context], list[Finding]]] = {}


def detector(kind: str):
    def register(fn):
        DETECTORS[kind] = fn
        return fn

    return register


def _finding(rule: Rule, ctx: Context, line: int, extra: str = "") -> Finding:
    return Finding(
        rule=rule.id,
        severity=rule.severity,
        path=ctx.relpath,
        line=line,
        message=rule.message.strip() + (f" [{extra}]" if extra else ""),
        title=rule.title,
    )


@detector("forbidden_call")
def _forbidden_call(rule: Rule, ctx: Context) -> list[Finding]:
    """Flag `<anything>.<attr>(...)`. Attribute-based rather than name-resolved
    on purpose: resolving `admin` back to an AdminClient would need type
    inference, and the false-positive cost of flagging a same-named method on
    an unrelated object is far lower than the cost of missing the real one."""
    cfg = rule.detector or {}
    attr = cfg["attr"]
    out = []
    for node in ast.walk(ctx.tree):
        if (
            isinstance(node, ast.Call)
            and isinstance(node.func, ast.Attribute)
            and node.func.attr == attr
        ):
            out.append(_finding(rule, ctx, node.lineno, f"call to .{attr}()"))
    return out


@detector("forbidden_kwarg")
def _forbidden_kwarg(rule: Rule, ctx: Context) -> list[Finding]:
    """Flag `<anything>.<attr>(..., <kwarg>=...)`. The call itself is fine; it
    is the keyword that changes it from a read into a write."""
    cfg = rule.detector or {}
    attr, kwarg = cfg["attr"], cfg["kwarg"]
    out = []
    for node in ast.walk(ctx.tree):
        if (
            isinstance(node, ast.Call)
            and isinstance(node.func, ast.Attribute)
            and node.func.attr == attr
            and any(k.arg == kwarg for k in node.keywords)
        ):
            out.append(_finding(rule, ctx, node.lineno, f".{attr}({kwarg}=...)"))
    return out


@detector("import_location")
def _import_location(rule: Rule, ctx: Context) -> list[Finding]:
    """Flag `from WRONG import Symbol` where the symbol table names another
    module as the only real exporter."""
    symbols: dict[str, str] = (rule.detector or {})["symbols"]
    out = []
    for node in ast.walk(ctx.tree):
        if not isinstance(node, ast.ImportFrom) or node.module is None:
            continue
        for alias in node.names:
            want = symbols.get(alias.name)
            if want is not None and node.module != want:
                out.append(
                    _finding(
                        rule,
                        ctx,
                        node.lineno,
                        f"{alias.name} is exported by {want}, not {node.module}",
                    )
                )
    return out


@detector("require_import")
def _require_import(rule: Rule, ctx: Context) -> list[Finding]:
    cfg = rule.detector or {}
    module, name = cfg["module"], cfg["name"]
    for node in ast.walk(ctx.tree):
        if isinstance(node, ast.ImportFrom) and node.module == module:
            if any(a.name == name for a in node.names):
                return []
    return [_finding(rule, ctx, 1, f"from {module} import {name}")]


@detector("require_header")
def _require_header(rule: Rule, ctx: Context) -> list[Finding]:
    """Whitespace-normalised containment over the first 2 KB. Normalising
    matters: the ASF header is comment-wrapped and line-broken differently in
    different files, so an exact string match would produce false positives on
    files that are perfectly correct."""
    needle = " ".join((rule.detector or {})["contains"].split())
    haystack = " ".join(ctx.source[:2048].split())
    return [] if needle in haystack else [_finding(rule, ctx, 1)]


@detector("require_class_attr")
def _require_class_attr(rule: Rule, ctx: Context) -> list[Finding]:
    cfg = rule.detector or {}
    suffix, attr = cfg["base_suffix"], cfg["attr"]
    out = []
    for node in ast.walk(ctx.tree):
        if not isinstance(node, ast.ClassDef):
            continue
        base_names = [
            b.id if isinstance(b, ast.Name) else b.attr if isinstance(b, ast.Attribute) else ""
            for b in node.bases
        ]
        if not any(b.endswith(suffix) for b in base_names):
            continue
        declared = False
        for stmt in node.body:
            targets = (
                stmt.targets
                if isinstance(stmt, ast.Assign)
                else [stmt.target] if isinstance(stmt, ast.AnnAssign) else []
            )
            if any(isinstance(t, ast.Name) and t.id == attr for t in targets):
                declared = True
                break
        if not declared:
            out.append(_finding(rule, ctx, node.lineno, f"class {node.name}"))
    return out


@detector("paired_call")
def _paired_call(rule: Rule, ctx: Context) -> list[Finding]:
    """Module-level pairing: if `requires` appears anywhere, `pair` must too.

    Deliberately coarse. Proving a teardown actually runs on the failure path
    would need control-flow analysis; proving the author thought about teardown
    at all is a one-line check that catches the real defect in upstream's
    suite. Coarse and honest beats precise and unwritten.
    """
    cfg = rule.detector or {}
    need, pair = cfg["requires"], cfg["pair"]
    seen_need = seen_pair = None
    for node in ast.walk(ctx.tree):
        if isinstance(node, ast.Call) and isinstance(node.func, ast.Attribute):
            if node.func.attr == need and seen_need is None:
                seen_need = node.lineno
            if node.func.attr == pair:
                seen_pair = node.lineno
    if seen_need is not None and seen_pair is None:
        return [_finding(rule, ctx, seen_need, f"{need}() with no {pair}()")]
    return []


def _split_overlay(rel: str, src_root: str) -> tuple[str, str]:
    """Split `rel` into (overlay prefix, path below src_root).

    A rule's roots are written as upstream paths -- `providers/apache/kafka/...`
    -- because that is where the convention actually lives. But the same tree
    can appear under a prefix: `contribution/` holds the PR laid out at its
    upstream paths, so `contribution/providers/apache/kafka/src/...` is the same
    file the rule is about.

    Anchoring on the LAST occurrence of the root, rather than requiring the path
    to start with it, is what lets one rule govern both. The alternative --
    duplicating every path-based rule with a `contribution/`-prefixed twin --
    guarantees the two copies drift, and the copy that drifts is the one nobody
    runs.

    Raises SkipRule if the root does not appear at all; a rule whose root is
    absent from the checkout was not evaluated, and the caller reports that
    rather than counting the file as clean.
    """
    marker = src_root.rstrip("/") + "/"
    idx = rel.rfind(marker)
    if idx == -1:
        raise SkipRule(f"{rel} is outside src_root {src_root!r}")
    return rel[:idx], rel[idx + len(marker) :]


@detector("path_mirror")
def _path_mirror(rule: Rule, ctx: Context) -> list[Finding]:
    cfg = rule.detector or {}
    src_root, test_root = cfg["src_root"], cfg["test_root"]
    prefix = cfg.get("prefix", "test_")

    rel = ctx.relpath.replace(os.sep, "/")
    overlay, tail = _split_overlay(rel, src_root)

    # Resolved inside the same overlay as the source file. Checking the upstream
    # test root for a contribution/ file would look in a tree the PR does not
    # touch and pass on a test that was never written.
    test_root = overlay + test_root.rstrip("/")
    if not os.path.isdir(os.path.join(ctx.root, test_root)):
        raise SkipRule(f"test root {test_root!r} is not in this checkout")

    head, name = os.path.split(tail)
    expected = os.path.join(test_root, head, prefix + name).replace(os.sep, "/")
    if os.path.isfile(os.path.join(ctx.root, expected)):
        return []
    return [_finding(rule, ctx, 1, f"expected {expected}")]


@detector("registry_sync")
def _registry_sync(rule: Rule, ctx: Context) -> list[Finding]:
    """The module's dotted path must appear in the registry file.

    Plain text containment rather than parsing provider.yaml: upstream owns
    that schema and it is not ours to track. Containment cannot be fooled in
    the direction that matters -- if the dotted name is absent, it is absent.
    """
    cfg = rule.detector or {}
    rel = ctx.relpath.replace(os.sep, "/")
    overlay, tail = _split_overlay(rel, cfg["src_root"])

    # Same overlay rule as path_mirror: a contribution/ operator must be
    # registered in the provider.yaml the PR ships, not in an upstream one that
    # is not part of the change.
    registry_rel = overlay + cfg["registry"]
    registry = os.path.join(ctx.root, registry_rel)
    if not os.path.isfile(registry):
        raise SkipRule(f"registry {registry_rel!r} is not in this checkout")

    dotted = tail[:-3].replace("/", ".") if tail.endswith(".py") else tail.replace("/", ".")
    with open(registry, encoding="utf-8") as fh:
        if dotted in fh.read():
            return []
    # Names the registry actually read, not cfg["registry"]. Under an overlay
    # those differ, and pointing an engineer at a file the linter never opened
    # is how you lose ten minutes editing the wrong provider.yaml.
    return [_finding(rule, ctx, 1, f"{dotted} absent from {registry_rel}")]


# ---------------------------------------------------------------------------
# Loading
# ---------------------------------------------------------------------------

REQUIRED_FIELDS = ("id", "pack", "title", "severity", "owner", "applies_to", "message")


def load_rules(rules_dir: str) -> list[Rule]:
    if not os.path.isdir(rules_dir):
        die(f"{rules_dir}: not a directory. Point --rules at the rule pack.")

    paths = sorted(
        os.path.join(rules_dir, f)
        for f in os.listdir(rules_dir)
        if f.endswith((".yaml", ".yml"))
    )
    if not paths:
        die(f"{rules_dir}: no .yaml rules found. Refusing to report a clean run.")

    rules: list[Rule] = []
    seen: dict[str, str] = {}
    for path in paths:
        with open(path, encoding="utf-8") as fh:
            raw = yaml.safe_load(fh)
        if not isinstance(raw, dict):
            die(f"{path}: expected a YAML mapping at the top level")

        missing = [f for f in REQUIRED_FIELDS if f not in raw]
        if missing:
            die(f"{path}: missing required field(s) {missing}")

        if raw["severity"] not in SEVERITIES:
            die(f"{path}: severity {raw['severity']!r} not in {list(SEVERITIES)}")

        if raw["id"] in seen:
            die(f"{path}: duplicate rule id {raw['id']!r}, already defined in {seen[raw['id']]}")
        seen[raw["id"]] = path

        det = raw.get("detector")
        if det is not None:
            if not isinstance(det, dict) or "kind" not in det:
                die(f"{path}: detector must be null or a mapping with a 'kind'")
            # Design rule 1. A typo here must stop the run, not disable a check.
            if det["kind"] not in DETECTORS:
                die(
                    f"{path}: unknown detector kind {det['kind']!r}.\n"
                    f"Known kinds: {sorted(DETECTORS)}\n"
                    f"Refusing to lint -- an unrecognised kind would silently check nothing."
                )

        rules.append(
            Rule(
                id=raw["id"],
                pack=raw["pack"],
                title=raw["title"],
                severity=raw["severity"],
                owner=raw["owner"],
                applies_to=list(raw["applies_to"]),
                detector=det,
                message=raw["message"],
                rationale=raw.get("rationale", ""),
                evidence=raw.get("evidence", ""),
                replacement=raw.get("replacement", ""),
                references=list(raw.get("references", []) or []),
                source_file=path,
            )
        )
    return rules


def collect_files(paths: list[str], root: str) -> list[str]:
    out: list[str] = []
    # Hidden directories are skipped wholesale, which covers .git, .venv-*, and
    # every tool cache without maintaining a list that goes stale. A dot-dir
    # passed explicitly on the command line is still linted -- the filter only
    # applies while descending.
    skip_dirs = {"venv", "env", "__pycache__", "node_modules", "site-packages", "build", "dist"}
    for p in paths:
        ap = os.path.abspath(p)
        if os.path.isfile(ap):
            out.append(ap)
        elif os.path.isdir(ap):
            for dirpath, dirnames, filenames in os.walk(ap):
                dirnames[:] = [
                    d for d in dirnames if d not in skip_dirs and not d.startswith(".")
                ]
                out.extend(
                    os.path.join(dirpath, f) for f in filenames if f.endswith(".py")
                )
        else:
            die(f"{p}: no such file or directory")
    return sorted(set(out))


# ---------------------------------------------------------------------------
# Linting
# ---------------------------------------------------------------------------


def lint(rules: list[Rule], files: list[str], root: str) -> tuple[list[Finding], dict]:
    findings: list[Finding] = []
    fired: dict[str, int] = {r.id: 0 for r in rules}
    evaluated: dict[str, int] = {r.id: 0 for r in rules}
    skipped: dict[str, str] = {}

    for abspath in files:
        relpath = os.path.relpath(abspath, root).replace(os.sep, "/")
        applicable = [
            r for r in rules if r.detector is not None and matches(relpath, r.applies_to)
        ]
        if not applicable:
            continue

        try:
            with open(abspath, encoding="utf-8") as fh:
                source = fh.read()
        except OSError as exc:
            findings.append(
                Finding("LINT-IO", "error", relpath, 1, f"could not read: {exc}")
            )
            continue

        try:
            tree = ast.parse(source, filename=abspath)
        except SyntaxError as exc:
            # Report rather than crash: a scaffold that emits invalid Python is
            # exactly the case this tool exists to catch, and a traceback would
            # bury it.
            findings.append(
                Finding(
                    "LINT-SYNTAX",
                    "error",
                    relpath,
                    exc.lineno or 1,
                    f"could not parse: {exc.msg}",
                )
            )
            continue

        ctx = Context(root=root, relpath=relpath, abspath=abspath, source=source, tree=tree)

        for r in applicable:
            try:
                hits = DETECTORS[r.detector["kind"]](r, ctx)
            except SkipRule as exc:
                skipped.setdefault(r.id, str(exc))
                continue
            except Exception as exc:  # design rule 2: fail closed
                hits = [
                    Finding(
                        r.id,
                        "error",
                        relpath,
                        1,
                        f"detector {r.detector['kind']!r} raised "
                        f"{type(exc).__name__}: {exc} (failing closed)",
                        r.title,
                    )
                ]
            evaluated[r.id] += 1
            fired[r.id] += len(hits)
            findings.extend(hits)

    findings.sort(key=lambda f: (f.path, f.line, f.rule))
    # A rule counts as "not evaluated" only if it ran against nothing at all.
    # A rule that skipped one file and checked forty others has coverage; saying
    # otherwise would make the honest-reporting line noisy enough to be ignored,
    # which defeats the purpose of having it.
    not_evaluated = {rid: why for rid, why in skipped.items() if evaluated[rid] == 0}
    coverage = {
        "rules_total": len(rules),
        "rules_with_detector": sum(1 for r in rules if r.detector is not None),
        "rules_advisory_only": sorted(r.id for r in rules if r.detector is None),
        "rules_not_evaluated": not_evaluated,
        "files_scanned": len(files),
        "fired": {k: v for k, v in fired.items() if v},
        "evaluated": {k: v for k, v in evaluated.items() if v},
    }
    return findings, coverage


# ---------------------------------------------------------------------------
# Output
# ---------------------------------------------------------------------------


def render(findings: list[Finding], coverage: dict, rules: list[Rule], summary: bool) -> str:
    by_id = {r.id: r for r in rules}
    lines: list[str] = []

    if findings:
        for f in findings:
            lines.append(f"{f.path}:{f.line}: {f.severity.upper()} {f.rule}  {f.message}")
            rule = by_id.get(f.rule)
            if rule and rule.replacement.strip():
                first = rule.replacement.strip().splitlines()[0]
                lines.append(f"    fix: {first}")
                if len(rule.replacement.strip().splitlines()) > 1:
                    lines.append(f"    see: {rule.source_file} (full replacement)")
            elif rule:
                lines.append(f"    see: {rule.source_file}")
        lines.append("")

    errors = sum(1 for f in findings if f.severity == "error")
    advisories = sum(1 for f in findings if f.severity == "advisory")
    lines.append(
        f"{coverage['files_scanned']} file(s) scanned, "
        f"{coverage['rules_with_detector']}/{coverage['rules_total']} rule(s) enforceable, "
        f"{errors} error(s), {advisories} advisory"
    )

    # Design rule 3. A clean run must never be mistaken for full coverage.
    advisory_only = coverage["rules_advisory_only"]
    if advisory_only:
        lines.append(
            f"  advisory, no detector (context + docs only): {', '.join(advisory_only)}"
        )
    for rid, why in sorted(coverage["rules_not_evaluated"].items()):
        lines.append(f"  NOT EVALUATED  {rid}: {why}")

    if summary:
        lines.append("")
        lines.append("rule coverage:")
        width = max(len(r.id) for r in rules)
        for r in rules:
            if r.detector is None:
                state = "advisory"
            elif r.id in coverage["rules_not_evaluated"]:
                state = "not evaluated"
            else:
                n = coverage["evaluated"].get(r.id, 0)
                hits = coverage["fired"].get(r.id, 0)
                state = f"{n} file(s) checked, {hits} hit(s)"
            lines.append(f"  {r.id.ljust(width)}  {r.owner.ljust(14)}  {state}")

    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(
        description="Deterministic convention linter over rules/*.yaml. No LLM.",
        epilog="Exit 0 clean, 1 violations, 2 bad usage or malformed rule pack.",
    )
    ap.add_argument("paths", nargs="*", default=["."], help="files or directories to lint")
    ap.add_argument("--rules", default="rules", help="rule pack directory (default: rules)")
    ap.add_argument("--root", default=".", help="repo root that applies_to globs are relative to")
    ap.add_argument("--json", action="store_true", help="emit findings as JSON")
    ap.add_argument("--output", metavar="FILE", help="also write the JSON report here")
    ap.add_argument("--summary", action="store_true", help="print per-rule coverage")
    ap.add_argument(
        "--advisory-as-error",
        action="store_true",
        help="fail the run on advisory findings too (off by default)",
    )
    args = ap.parse_args(argv)

    root = os.path.abspath(args.root)
    rules = load_rules(args.rules)
    files = collect_files(args.paths or ["."], root)
    findings, coverage = lint(rules, files, root)

    payload = {
        "findings": [f.__dict__ for f in findings],
        "coverage": coverage,
        "rules": [
            {"id": r.id, "pack": r.pack, "severity": r.severity, "owner": r.owner,
             "title": r.title, "enforceable": r.detector is not None}
            for r in rules
        ],
    }

    if args.output:
        try:
            parent = os.path.dirname(os.path.abspath(args.output))
            os.makedirs(parent, exist_ok=True)
            with open(args.output, "w", encoding="utf-8") as fh:
                json.dump(payload, fh, indent=2)
                fh.write("\n")
        except OSError as exc:
            die(f"could not write report {args.output!r}: {exc}")

    print(json.dumps(payload, indent=2) if args.json
          else render(findings, coverage, rules, args.summary))

    blocking = [
        f for f in findings
        if f.severity == "error" or (args.advisory_as_error and f.severity == "advisory")
    ]
    return EXIT_VIOLATIONS if blocking else EXIT_CLEAN


if __name__ == "__main__":
    try:
        sys.exit(main())
    except KeyboardInterrupt:
        sys.exit(130)
