#!/usr/bin/env python3
"""Turn a GitHub Actions workflow into a shell script you can run before pushing.

    python tools/workflow_dryrun.py .github/workflows/stag-tests.yml -o /tmp/run.sh
    bash /tmp/run.sh

The problem this solves: a self-hosted workflow can only be debugged by pushing.
Every typo costs a commit, a run, and a wait, and the pressure to get green
pushes people toward `git commit --amend --no-verify` loops that leave a
dishonest history. Worse, the debugging happens on the shared box either way --
so you may as well run it there deliberately instead of through the runner.

This extracts each step's `run:` body, in order, with the job's `env:` exported,
and wraps each one so a failure is reported and the rest still run. That last
part matters: the runner stops at the first red step, so you find one bug per
push. This finds all of them in one pass.

It found a real one the first time it was used: `uv venv .venv-tools` exits 2 on
a runner that reuses its workspace, in stag-tests.yml AND latently in
promote-prod.yml.

WHAT IT DOES NOT EMULATE, and you must not read a green run here as a green run
there:

  * `uses:` steps. actions/checkout, actions/upload-artifact and friends are
    skipped with a printed SKIP line. In particular nothing cleans the
    workspace, which is precisely why the .venv-tools bug was visible here and
    is normally hidden by checkout's `git clean -ffdx`.
  * `if:` conditions on steps and jobs. Everything runs.
  * secrets, GITHUB_TOKEN, the API, and `${{ github.* }}` beyond workspace.
  * GITHUB_OUTPUT and step outputs. GITHUB_ENV and GITHUB_PATH are emulated
    approximately -- appended and re-read between steps, which is close enough
    for PATH but does not survive the way the runner's does.
  * matrix, services, containers, concurrency, timeouts.

`${{ env.FOO }}` becomes the shell reference `${FOO}`, and `${{ github.workspace }}`
becomes `$PWD`. Any OTHER `${{ ... }}` -- inputs, secrets, needs, github.event --
is a hard error: leaving it in would put the literal text into the script, and a
shell script containing `${{ inputs.group }}` fails in a way that looks like a
quoting problem rather than a missing feature. Pass --allow-expressions to force
it through and accept that the rehearsal is no longer faithful.
"""

from __future__ import annotations

import argparse
import re
import shlex
import sys

import yaml

EXPRESSION = re.compile(r"\$\{\{\s*([^}]+?)\s*\}\}")

# Contexts with an honest shell equivalent. Values are SHELL text, evaluated
# when the script runs rather than when it is generated, so a rehearsal script
# stays correct if it is copied to another box -- which is the normal case here,
# since these workflows only run on self-hosted runners.
#
# `runner.temp` is deliberately absent. int-tests.yml has a long comment about
# why ${{ runner.temp }} is unusable at job level, and silently supplying it
# here would rehearse a workflow that cannot exist.
CONTEXT_SHELL = {
    "github.workspace": "$PWD",
}


def _shell_double_quote(value: str) -> str:
    """Quote for bash, leaving `$` live so CONTEXT_SHELL substitutions evaluate.

    shlex.quote() would be safer in general and is what step bodies do not need
    (they are emitted verbatim), but it single-quotes, which would turn the
    `$PWD` above into the literal four characters. Workflow env values are
    repo-controlled text, not untrusted input, so escaping `"`, `\\` and
    backtick is the right trade here. Untrusted values reach these workflows
    through `inputs`, which this tool refuses outright.
    """
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"').replace("`", "\\`") + '"'


PREAMBLE = """#!/usr/bin/env bash
# GENERATED by tools/workflow_dryrun.py from {source} (job: {job})
# Not a substitute for a real run -- see the module docstring for what is NOT
# emulated. Re-generate rather than editing.
set -uo pipefail
cd "$(dirname "$0")"

: "${{GITHUB_STEP_SUMMARY:=$(mktemp)}}"; export GITHUB_STEP_SUMMARY
: "${{GITHUB_ENV:=$(mktemp)}}";          export GITHUB_ENV
: "${{GITHUB_PATH:=$(mktemp)}}";         export GITHUB_PATH
: > "$GITHUB_STEP_SUMMARY"; : > "$GITHUB_ENV"; : > "$GITHUB_PATH"
FAILED=()
"""

STEP = """
echo
echo "== {label} =="
(
{body}
)
rc=$?
if [ $rc -eq 0 ]; then
  echo "  -> ok"
else
  echo "  -> FAILED (exit $rc)"
  FAILED+=({label_q})
fi
# Approximate the runner's file commands between steps.
set -a; . "$GITHUB_ENV"; set +a
PATH="$(tr '\\n' ':' < "$GITHUB_PATH")$PATH"; export PATH
"""

EPILOGUE = """
echo
echo "=== step summary written by the workflow ==="
cat "$GITHUB_STEP_SUMMARY"
echo
if [ ${#FAILED[@]} -eq 0 ]; then
  echo "ALL STEPS PASSED"
  exit 0
fi
echo "FAILED STEPS (${#FAILED[@]}):"
printf '  %s\\n' "${FAILED[@]}"
exit 1
"""


def resolve_expressions(text: str, env: dict, *, allow: bool, where: str) -> str:
    """Substitute `${{ env.X }}`; refuse anything else."""
    unresolved = []

    def replace(match):
        expr = match.group(1)
        if expr in CONTEXT_SHELL:
            return CONTEXT_SHELL[expr]
        # `env.X` becomes a shell reference, NOT the value from the env: block.
        # GitHub resolves env.* against the accumulated runtime environment,
        # which includes anything a previous step appended to $GITHUB_ENV --
        # int-tests.yml computes REPO_DIR that way precisely because
        # ${{ runner.temp }} is unavailable at job level. Substituting the
        # static value here would resolve REPO_DIR to nothing and silently
        # rehearse `cd ""`. As a shell reference under `set -u` it aborts and
        # names the variable instead.
        if expr.startswith("env."):
            return "${" + expr[len("env."):] + "}"
        unresolved.append(expr)
        return match.group(0)

    out = EXPRESSION.sub(replace, text)
    if unresolved and not allow:
        raise SystemExit(
            f"{where}: cannot resolve {sorted(set(unresolved))}.\n"
            "These would be left as literal text in the generated script, which "
            "fails as a confusing shell error rather than as a missing value.\n"
            "Supply them as environment variables and reference them as $VAR in "
            "the workflow, or re-run with --allow-expressions to emit them as-is."
        )
    return out


def generate(path: str, job_name: str | None, *, allow: bool) -> str:
    with open(path) as fh:
        doc = yaml.safe_load(fh)
    jobs = doc.get("jobs") or {}
    if not jobs:
        raise SystemExit(f"{path}: no jobs")
    if job_name is None:
        if len(jobs) > 1:
            raise SystemExit(
                f"{path} has {len(jobs)} jobs ({', '.join(jobs)}); pick one with --job"
            )
        job_name = next(iter(jobs))
    if job_name not in jobs:
        raise SystemExit(f"{path}: no job named {job_name!r}. Have: {', '.join(jobs)}")

    job = jobs[job_name]
    env = dict(doc.get("env") or {})
    env.update(job.get("env") or {})

    parts = [PREAMBLE.format(source=path, job=job_name)]
    for key, value in env.items():
        rendered = resolve_expressions(str(value), env, allow=allow, where=f"env.{key}")
        parts.append(f"export {key}={_shell_double_quote(rendered)}")
    parts.append("")

    ran = 0
    for index, step in enumerate(job.get("steps") or []):
        label = step.get("name") or step.get("uses") or f"step {index}"
        if "run" not in step:
            parts.append(f'echo "SKIP (uses: {step.get("uses")}): {label}"')
            continue
        if step.get("shell") not in (None, "bash", "sh"):
            parts.append(f'echo "SKIP (shell: {step["shell"]}): {label}"')
            continue
        body = resolve_expressions(step["run"], env, allow=allow, where=f"step {label!r}")
        if step.get("working-directory"):
            wd = resolve_expressions(
                str(step["working-directory"]), env, allow=allow, where=f"step {label!r} cwd"
            )
            body = f"cd {_shell_double_quote(wd)}\n{body}"
        parts.append(
            STEP.format(
                # Quotes in a name would break the echo; the label is cosmetic.
                label=label.replace('"', "").replace("'", ""),
                label_q=shlex.quote(label),
                body=body,
            )
        )
        ran += 1

    if not ran:
        raise SystemExit(f"{path}: job {job_name!r} has no `run:` steps to rehearse")
    parts.append(EPILOGUE)
    return "\n".join(parts)


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("workflow")
    parser.add_argument("--job", help="job id; required when the file has more than one")
    parser.add_argument("-o", "--output", help="write here instead of stdout")
    parser.add_argument(
        "--allow-expressions",
        action="store_true",
        help="emit unresolved ${{ }} as literal text instead of failing",
    )
    args = parser.parse_args(argv)

    script = generate(args.workflow, args.job, allow=args.allow_expressions)
    if args.output:
        with open(args.output, "w") as fh:
            fh.write(script)
        print(f"wrote {args.output}  --  run it with: bash {args.output}", file=sys.stderr)
    else:
        sys.stdout.write(script)
    return 0


if __name__ == "__main__":
    sys.exit(main())
