name: Infrastructure Smoke Test

on:
  workflow_dispatch:

jobs:
  integration-smoke:
    runs-on: self-hosted

    steps:
      - name: Show host
        run: |
          echo "Running on:"
          hostname
          uname -a

      - name: Check basic tools
        run: |
          git --version
          curl --version | head -1
          jq --version

      - name: Check Docker
        run: |
          docker --version
          docker compose version
          docker ps

      - name: Check Kafka
        run: |
          docker exec kafka \
            /opt/kafka/bin/kafka-topics.sh \
            --bootstrap-server localhost:9092 \
            --list
